---
title: "Iteration and List columns"
output: github_document
---

```{r}
library(tidyverse)

set.seed(1)

```


# list

```{r}
l = list(
  vec_numeric = 5:8,
  mat         = matrix(1:8, 2, 4),
  vec_logical = c(TRUE, FALSE),
  summary     = summary(rnorm(1000))
)
```

access list item($ is not recommended)
```{r}
l$vec_numeric

l[[1]]

l[["vec_numeric"]]
```

# loops

```{r}
list_norms = 
  list(
    a = rnorm(20, 3, 1),
    b = rnorm(20, 0, 5),
    c = rnorm(20, 10, .2),
    d = rnorm(20, -3, 1)
  )


```

# mean and sd fuction
```{r}
mean_sd = function(x){
  if(!is.numeric(x)){
    stop("z-scores only work for numbers")
  }
  
  if(length(x) <3){
    stop("z-scores only work for 3 or more numbers")
  }

  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

`for` loop
```{r}
output = vector("list", 4)

for (i in 1:4) {
  output[[i]] = mean_sd(list_norms[[i]])
}

output 
```

map
```{r}
map(list_norms, mean_sd)
```

outher fuctions
```{r}
map(list_norms, median)
map(list_norms, summary)
```

map variant
```{r}
map(list_norms, median)

map_df(list_norms, mean_sd)
```

# list columns
```{r}
listcol_df = 
  tibble(
    name = c("a", "b", "c", "d"),
    norm = list_norms
  )

listcol_df[["norm"]]

map(listcol_df[["norm"]], mean_sd)
```

add list columns
```{r}
listcol_df %>% 
  mutate(
    m_sd = map(norm, mean_sd)
  )


listcol_df %>% 
  mutate(
    m_sd = map_df(norm, mean_sd)
  )
```

# nest
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())
```

```{r}
weather_nest_df = 
  weather_df %>% 
  nest(data = date:tmin)

weather_nest_df[["data"]]
```


```{r}
weather_nest_df[['data']][[1]]

lm(tmax ~ tmin, data = weather_nest_df[['data']][[1]])
```

```{r}
weather_lm = function(df){
  lm(tmax ~ tmin, data = df)
}
  

weather_lm(weather_nest_df[['data']][[1]])

map(weather_nest_df[['data']], weather_lm)
```

```{r}
weather_nest_df %>% 
  mutate(
    model = map(data, weather_lm)
  )
```

unnesting
```{r}
weather_nest_df %>% 
  unnest(data)
```

# example

```{r}
library(rvest)

read_page_reviews <- function(url) {
  
  html = read_html(url)
  
  review_titles = 
    html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)
  
  tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
}

```

```{r}
url_base = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="
```


```{r}
vec_urls = str_c(url_base, 1:5)
output = vector("list", 5)

for (i in 1:5) {
  output[[i]] = read_page_reviews(vec_urls[[i]])
}

dynamite_reviews = bind_rows(output)
```

```{r}
dynamite_reviews = map_df(vec_urls, read_page_reviews)
```

```{r}
dynamite_reviews = 
  tibble(
    page = 1:5,
    urls = str_c(url_base, page)) %>% 
  mutate(reviews = map(urls, read_page_reviews)) %>% 
  unnest(reviews)

dynamite_reviews %>% 
  select(-urls) %>% 
  view()
```

