---
title: "Writing Functions"
output: github_document
---

```{r, include = FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(rvest)

knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)

theme_set(theme_minimal() + theme(legend.position = "bottom"))

options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)

scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
```


# Z-scores

z-score of a list of numbers 
```{r}
x_vec = rnorm(25, mean=7, sd=4)

(x_vec-mean(x_vec)) / sd(x_vec)
```

Function for standardization
```{r}
z_scores = function(x){
  if(!is.numeric(x)){
    stop("z-scores only work for numbers")
  }
  
  if(length(x) <3){
    stop("z-scores only work for 3 or more numbers")
  }

 z = (x-mean(x)) / sd(x)
 
 z
}
```

```{r}
z_scores(x=x_vec)
z_scores(x=1:10)
z_scores(x=rbinom(1000, 1, 0.6))

z_scores(x=3)
z_scores(x="hellow")
```


# multiple outputs

mean and sd
```{r}
mean_sd = function(x){
  if(!is.numeric(x)){
    stop("z-scores only work for numbers")
  }
  
  if(length(x) <3){
    stop("z-scores only work for 3 or more numbers")
  }

  mean_x = mean(x)
  sd_x = sd(x)
  
  tibble(
    mean = mean_x,
    sd = sd_x
  )
}
```

```{r}
mean_sd(x=x_vec)
mean_sd(x=rbinom(1000, 1, 0.6))
```

# simulation and multiple inputs

```{r}
x_vec = rnorm(n=25, mean=7, sd=4)

tibble(
  mean = mean(x_vec),
  sd = sd(x_vec)
)
```

```{r}
sim_mean_sd = function(n_obs, t_mean=7, t_sd=4){
  
  x = rnorm(n=n_obs, mean=t_mean, sd=t_sd)

  tibble(
    mean = mean(x),
    sd = sd(x)
  )
}
```

```{r}
sim_mean_sd(n_obs=25, t_mean=10, t_sd=5)
sim_mean_sd(n_obs=25)
sim_mean_sd(25000)
sim_mean_sd(25000, 10)
sim_mean_sd(25000, t_sd = 10)
```

# Review

original code:

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

dynamite_html = read_html(url)

review_titles = 
  dynamite_html %>%
  html_nodes(".a-text-bold span") %>%
  html_text()

review_stars = 
  dynamite_html %>%
  html_nodes("#cm_cr-review_list .review-rating") %>%
  html_text() %>%
  str_extract("^\\d") %>%
  as.numeric()

review_text = 
  dynamite_html %>%
  html_nodes(".review-text-content span") %>%
  html_text() %>% 
  str_replace_all("\n", "") %>% 
  str_trim()

reviews = tibble(
  title = review_titles,
  stars = review_stars,
  text = review_text
)
```


```{r}
read_page_review = function(url){
  
  dynamite_html = read_html(url)

  review_titles = 
    dynamite_html %>%
    html_nodes(".a-text-bold span") %>%
    html_text()
  
  review_stars = 
    dynamite_html %>%
    html_nodes("#cm_cr-review_list .review-rating") %>%
    html_text() %>%
    str_extract("^\\d") %>%
    as.numeric()
  
  review_text = 
    dynamite_html %>%
    html_nodes(".review-text-content span") %>%
    html_text() %>% 
    str_replace_all("\n", "") %>% 
    str_trim() %>% 
    str_subset("The media could not be loaded.", negate = TRUE) %>% 
    str_subset("^$", negate = TRUE)
  
  reviews = tibble(
    title = review_titles,
    stars = review_stars,
    text = review_text
  )
  
  reviews
}

```

```{r}
url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber=1"

read_page_review(url)
```

```{r}
base_url = "https://www.amazon.com/product-reviews/B00005JNBQ/ref=cm_cr_arp_d_viewopt_rvwer?ie=UTF8&reviewerType=avp_only_reviews&sortBy=recent&pageNumber="

vec_url = str_c(base_url, c(1,2,3,4,5))


dynamite_reviews = 
  bind_rows(
    read_page_review(vec_url[1]),
    read_page_review(vec_url[2]),
    read_page_review(vec_url[3]),
    read_page_review(vec_url[4]),
    read_page_review(vec_url[5])
  )

```

# example

```{r}

lotr_load_and_tidy = function(path, range, movie_name) {
  
  df = readxl::read_excel(path, range = range) %>%
    janitor::clean_names() %>%
    gather(key = sex, value = words, female:male) %>%
    mutate(race = str_to_lower(race),
           movie = movie_name)
  
  df
  
}

lotr_tidy = 
  bind_rows(
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "B3:D6", "fellowship_ring"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "F3:H6", "two_towers"),
    lotr_load_and_tidy("./data/LotR_Words.xlsx", "J3:L6", "return_king")) %>%
  select(movie, everything()) 
```







